### ISSUE TITLE
Use Guid for format:uuid in C#

### ISSUE THREAD

**Issue by codertimu** [zijianhuang/openapiclientgen#38]
It would be nice if the generator would produce `Guid` for the `format:uuid` type instead of `string`.
Example:

```yaml
Order:
  type: object
  properties:
    order_id:
      type: string
      nullable: true
    order_uuid:
      type: string
      format: uuid
      nullable: true
    created_date:
      type: string
      format: date-time
      nullable: true
```

```c#
public class Order
{
    [System.Text.Json.Serialization.JsonPropertyName("order_id")]
    public string OrderId { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("order_uuid")]
    public string OrderUuid { get; set; } // the type should be Guid

    [System.Text.Json.Serialization.JsonPropertyName("created_date")]
    public System.DateTimeOffset? CreatedDate { get; set; }
}
```
