### ISSUE TITLE
consider to support dynamic object

### ISSUE THREAD

**Issue by zijianhuang** [zijianhuang/openapiclientgen#53]
consider to support dynamic object

```yaml
    collections_add_metadataBody:
      content:
        application/json:
          schema:
            example:
              application/json:
                data:
                  attributes:
                    guid: test0
                    subjects: 5fd228b7e64e1300aa99ee15
                    volume: test
                  type: collected-metadata
            type: object
      required: true
```
like the one in osf.io.

https://learn.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject
